---
name:        "File"
description: "Create a file"
branding:
  color: "gray-dark"
  icon:  "file-text"
inputs:
  content:
    description: "file content"
    required:    true
  encoding:
    description: "optional file content encoding [ base64 | base58 | base32 ]"
    required:    false
  path:
    description: "optional file path, will be generated if omitted"
    required:    false
outputs:
  path:
    description: "resulting file path"
runs:
  using: "docker"
  image: 'docker://akabos/action-file:v1.0.0'
